
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

alert: !include alerts.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

lovelace: !include lovelace.yaml

# Groups
#  | https://www.home-assistant.io/integrations/group#yaml-configuration
light: !include groups/lights.yaml

# HACS Frontend
frontend:
  themes: !include_dir_merge_named themes

http:
  ssl_certificate: certs/ames.lol/srv.crt
  ssl_key: certs/ames.lol/srv.key

shell_command:
    commit_and_push_config: /config/scripts/commit_and_push.sh

## --------------------- ##
# Integrations
## --------------------- ##

neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret

anniversaries: !include anniversaries.yaml

withings:
  use_webhook: true
