- platform: template
  sensors:
      lights_on:
        friendly_name: Lights on
        unit_of_measurement: 'on'
        value_template: >
          {{ states.light | selectattr("state","eq","on") | map(attribute="entity_id") | list | count }}

## --------------------- ##
# Switchbot
## --------------------- ##

- platform: rest
  name: 'Bedroom E2 Curtain Position'
  resource: !secret switchbot_curtain_bedroom_e2_status_url
  method: GET
  scan_interval: 600
  headers:
      Authorization: !secret switchbot_token
      Content-Type: 'application/json'
  value_template: '{{ value_json.body.slidePosition }}'
  json_attributes_path: "$.body"
  json_attributes:
    - deviceId
    - deviceType
    - hubDeviceId
    - calibrate
    - group
    - moving
    - slidePosition

- platform: rest
  name: 'Bedroom 85 Curtain Position'
  resource: !secret switchbot_curtain_bedroom_85_status_url
  method: GET
  scan_interval: 600
  headers:
      Authorization: !secret switchbot_token
      Content-Type: 'application/json'
  value_template: '{{ value_json.body.slidePosition }}'
  json_attributes_path: "$.body"
  json_attributes:
    - deviceId
    - deviceType
    - hubDeviceId
    - calibrate
    - group
    - moving
    - slidePosition

## --------------------- ##
# TeslaMate
## --------------------- ##

- platform: template
  sensors:
    tesla_est_battery_range_mi:
      friendly_name: Estimated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (states('sensor.tesla_est_battery_range_km') | float / 1.609344) | round(2) }}

    tesla_rated_battery_range_mi:
      friendly_name: Rated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (states('sensor.tesla_rated_battery_range_km') | float / 1.609344) | round(2) }}

    tesla_ideal_battery_range_mi:
      friendly_name: Ideal Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      value_template: >
        {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609344) | round(2) }}

    tesla_odometer_mi:
      friendly_name: Odometer (mi)
      unit_of_measurement: mi
      icon_template: mdi:counter
      value_template: >
        {{ (states('sensor.tesla_odometer') | float / 1.609344) | round(2) }}

    tesla_speed_mph:
      friendly_name: Speed (MPH)
      unit_of_measurement: mph
      icon_template: mdi:speedometer
      value_template: >
        {{ (states('sensor.tesla_speed') | float / 1.609344) | round(2) }}

    tesla_elevation_ft:
      friendly_name: Elevation (ft)
      unit_of_measurement: ft
      icon_template: mdi:image-filter-hdr
      value_template: >
        {{ (states('sensor.tesla_elevation') | float * 3.2808 ) | round(2) }}
