- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_temperature
    - type: last_boot

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2)  }}'

- platform: min_max
  entity_ids:
    - sensor.kitchen_temperature
    - sensor.bedroom_temperature
    ## omitting as it is omitted from ecobee calculations
    # - sensor.spire_temperature  # entry (ecobee)
    - sensor.smartsensor_temperature  # living room
    - sensor.bathroom_motion_sensor_temperature
  type: mean
  name: home_temp_avg
